var html_strings = {
    "electricity": ["Electricity", "Elektriciteit"],
    "water": ["Water", "Water"],
    "gas": ["Gas", "Gas"],
    "temperature": ["Temperature", "Temperatuur"],
    "other": ["Other", "Andere"],
    "homelink": ["Home", "Start"],
    "statisticslink": ["Statistics", "Statistieken"],
    "sensorslink" : ["Sensors", "Sensoren"],
    "sociallink" : ["Social", "Sociaal"],
    "adminlink" : ["Admin", "Beheerder"],
    "reportlink" : ["Report", "Rapport"],
    "helplink" : ["Help Page", "Help Pagina"],
    "datalink" : ["Upload data", "Upload data"],
    "contact": ["Contact ", "Contacteer "],
    "about": ["About ", "Over "],
    "language": ["Language", "Taal"],
    "register": ["Signup", "Registreer"],
    "login": ["Login", "Inloggen"],
    "logout": ["Logout", "Afmelden"],
    "homepage_welcome": ["Welcome to", "Welkom bij"],
    "username": ["Username", "Gebruikersnaam"],
    "firstname": ["Firstname", "Voornaam"],
    "lastname": ["Lastname", "Achternaam"],
    "password": ["Password", "Paswoord"],
    "privacy": ["Privacy & Terms", "Privacy & Condities"], 
    "required_field": ["This field is required", "Dit veld is verplicht"],
    "login_error": ["Wrong username or password!", "Foute gebruikersnaam of paswoord!"],
    "back": ["Back", "Terug"],
    "invalid_email": ["Please input a valid email address", "Gelieve een geldig emailadres in te geven"], 
    "invalid_password": ["Password must contain at least 8 characters", "Paswoord moet minstens 8 tekens bevatten"],
    "signup_error": ["Email already exists.\nPlease login with your account.", "Emailadres bestaat al.\nGelieve in te loggen op dit account."],
    "description": ["Description", "Beschrijving"],
    "country": ["Country", "Land"],
    "city": ["City", "Stad"],
    "postalcode": ["ZIP / Postal Code", "Postcode"],
    "street": ["Street", "Straat"],
    "number": ["Number", "Huisnummer"],
    "unit_price": ["Usage cost (per unit)", "Verbruikskost (per eenheid)"],
    "edit_location": ["Edit location", "Locatie bewerken"],
    "add_location": ["Add location", "Locatie toevoegen"],
    "del_location": ["Delete location", "Locatie verwijderen"],
    "edit_sensor": ["Edit sensor", "Sensor bewerken"],
    "del_sensor": ["Delete sensor", "Sensor verwijderen"],
    "add_sensor": ["Add sensor", "Sensor toevoegen"],
    "save_changes": ["Save", "Opslaan"],
    "name": ["Name", "Naam"],
    "pick_loc": ["Choose your location", "Kies uw locatie"],
    "pick_type": ["Choose your type", "Kies uw type"],
    "locations": ["Locations", "Locaties"],
    "location": ["Location", "Locatie"],
    "mark_unimportant": ["Mark as unimportant", "Markeren als onbelangrijk"],
    "mark_important": ["Mark as important", "Markeren als belangrijk"],
    "confirm_title": ["Confirmation", "Bevestiging"],
    "confirm_text": ["This item will be removed permanently from your interface. Together with all its refered objects!!\nAre you sure you want to continue?", 
                     "Dit item zal voorgoed verwijderd worden uit uw interface. Samen met alle gerefereerde objecten!!\nBent u zeker dat u wilt doorgaan?"],
    "continue": ["Continue", "Doorgaan"],
    "cancel": ["Cancel", "Annuleren"],
    "share" : ["Share", "Deel"],
    "aggregate_loc" : ["Aggregate by location", "Groepeer per locatie"],
    "aggregate_type" : ["Aggregate by type", "Groepeer per type"],
    "aggregate_tag" : ["Aggregate by tag", "Groepeer per tag"],
    "aggregate_eur_per_unit" : ["Aggregate by Euro per Unit", "Groepeer per euro per unit"],
    "aggregate_user" : ["Aggregate by user", "Groepeer per user"],
    "open" : ["Open", "Openen"],
    "close" : ["Close", "Sluiten"],
    "delete_comment" : ["Delete comment", "Comment verwijderen"],
    "show_comments" : ["Show comments", "Comments tonen"],
    "hide_comments" : ["Hide comments", "Comments verbergen"],
    "comment_status" : ["Comment on this status...", "Comment op deze status..."],
    "find_friends" : ["Find friends", "Vrienden zoeken"],
    "create_group" : ["Create group", "Groep maken"],
    "join_group" : ["Join group", "Lid worden van een groep"],
    "group_name" : ["Group name", "Groepsnaam"],
    "group_public" : ["Public group", "Publieke groep"],
    "group_secret" : ["Secret group", "Geheime groep"],
    "create" : ["Create", "Aanmaken"],
    "my_profile" : ["My Profile", "Mijn Profiel"],
    "my_friends" : ["My Friends", "Mijn Vrienden"],
    "no_location_title" : ["No Locations Available", "Geen Locaties Beschikbaar"],
    "no_location_text" : ["It is not allowed to add sensors when you have not added any locations yet.\nPlease add a location first.",
                          "Het is niet toegestaan om sensors toe te voegen wanneer u nog geen locaties heeft toegevoegd.\nGelieve eerst een locatie aan te maken."],
    "ok" : ["Okay", "OK"],
    "add_friend" : ["Add friend", "Vriend toevoegen"],
    "box1_title" : ["Select sensors by locations, types or tags", "Selecteer sensors op basis van locaties, types or tags"],
    "box1_title_admin" : ["Select sensors by users", "Selecteer sensors op basis van users"],
    "box2_title" : ["Refine your selection by selecting sensors individually", "Verfijn uw zoekopdracht door sensors individueel te selecteren"],
    "box3_title" : ["Choose the timespan", "Kies de tijdspanne"],
    "box4_title" : ["Resulting graphs", "Resulterende grafieken"],
    "show_data" : ["Show data", "Toon data"],
    "merge_checkbox" : ["Merge if possible", "Samenvoegen indien mogelijk"],
    "show_data_from" : ["Show data from ", "Toon data van "],
    "amount" : ["number", "aantal"],
    "amount_help" : ["Amount of days/months/years you want to look back in time", "Aantal dagen/maanden/jaren terug, waarvan u de data wilt bekijken"],
    "start_date" : ["Start date", "Start datum"],
    "end_date" : ["End date", "Eind datum"],
    "pick_time_unit" : ["Pick a time unit", "Kies een tijdseenheid"],
    "raw" : ["Raw", "Ruw"],
    "hours" : ["Hours", "Uren"],
    "days" : ["Days", "Dagen"],
    "months" : ["Months", "Maanden"],
    "years" : ["Years", "Jaren"],
    "upload_file" : ["Upload a data file", "Laad een data file in"],
    "share_title" : ["Share the graph", "Deel de grafiek"],
    "share_text" : ["You can choose to post this graph on your own wall, visible to all of your friends, or in a group, visible to all the group members.",
                    "Je kan kiezen om deze grafiek op je prikbord te plaatsen, zichtbaar voor al je vrienden, of in een groep, zichtbaar voor alle leden."],
    "share_with" : ["Share with ", "Deel met "],
    "wall" : ["Wall", "Prikbord"],
    "pick_share" : ["choose a method", "kies een methode"],
    "data_title" : ["Upload data", "Upload data"],
    "data_text" : ["Generate a new data file through our elecsim script and upload this file with the following button.",
                   "Genereer een nieuwe data file met ons elecsim script en upload deze file met onderstaande knop."],
    "send" : ["Send", "Versturen"],
    "send_error" : ["Something went wrong while uploading your file, please try again", "Er ging iets mis bij het sturen van uw file, probeer aub opnieuw"],
    "down_config" : ["Download configuration file", "Download configuratie file"],
    "users" : ["Users", "Gebruikers"],
    "delete_friend" : ["Delete friend", "Vriend verwijderen"],
    "until" : ["until", "tot"],
    "input_status" : ["How are you feeling today?", "Wat ben je aan het doen?"],
    "post" : ["Post", "Plaats"],
    "delete_status" : ["Delete status", "Status verwijderen"],
    "group" : ["Group", "Groep"],
    "pick_group" : ["Pick group", "Kies een groep"],
    "input_status_group": ["What do you want to share with the group?", "Wat ben je aan het doen?"],
    "post_group": ["Post in group", "Gooi het in de groep"],
    "own_status" : ["Own status", "Eigen status"],
    "friend_status" : ["Status from ", "Status van "],
    "posted_on" : ["Posted on: ", "Geplaatst op: "],
    "no_tag" : ["No tags", "Geen tags"],
    "welcome_group" : ["Welcome in group: ", "Welkom in de groep: "],
    "members" : ["Members: ", "Leden: "],
    "leave_group" : ["Leave group", "Groep verlaten"],
    "report_title" : ["Title (click and type to make a title)", "Titel (klik en typ om een titel te maken)"],
    "report_comment" : ["comment (click and type to make a comment)", "comment (klik en typ om een comment te maken)"],
    "report_final_comment" : ["comment (click and type to make a final comment)", "comment (klik en typ om een finale comment te maken)"],
    "graph" : ["Graph", "Grafiek"],

    "static": ["Static Data", "Statische Data"],
    "live": ["Live Data", "Live Data"],
    "amount_back": ["Amount of time back", "Aantal tijdseenheden terug"],




	"faq_hp" : ["Home page", "Home pagina"],
	"faq_hp_quest_1" : ["How do i navigate on the site?", "Hoe navigeer ik op de website?"],
	"faq_hp_quest_2" : ["I heard there were extra features planned for the homepage, which features excactly?", "Ik heb gehoord dat er extra features zijn gepland voor de home pagina, dewelke juist?"],

	"faq_stp" : ["Statistics page", "Statistiek pagina"],
	"faq_stp_quest_1" : ["The 4 dropdowns and their basic usage.", "De 4 \"dropdown\" menus en hun gebruik."],
	"faq_stp_quest_2" : ["What does \"aggregate by...\" mean?", "Wat betekent \"Groepeer per...\"?"],

	"faq_sp" : ["Sensor page", "Sensor pagina"],
	"faq_sp_quest_1" : ["The sensors page looks broken, how do i fix this?", "De sensor pagina ziet er vreemd uit, hoe los ik dit op?"],
	"faq_sp_quest_2" : ["Adding a location/sensor", "Locatie/sensor toevoegen"],
	"faq_sp_quest_3" : ["Editing a location/sensor", "Locatie/sensor aanpassen"],
	"faq_sp_quest_4" : ["Deleting a location/sensor", "Locatie/sensor deleten"],
	"faq_sp_quest_5" : ["Extra features", "Extra snufjes"],

	"faq_shp" : ["Social home page", "Sociaal home pagina"],
	"faq_shp_quest_1" : ["The social page looks broken, how do i fix this?", "Het sociaal gedeelte van de website ziet er vreemd uit,  hoe los ik dit op?"],
	"faq_shp_quest_2" : ["Making/joining a group", "Groep maken/joinen"],
	"faq_shp_quest_3" : ["Getting new friends", "Vrienden toevoegen"],
	"faq_shp_quest_4" : ["Looking at the wall/profile of groups/friends", "Naar de wall / het profiel van een groep/vriend kijken"],

	"faq_spp" : ["Social profile page", "Sociaal profiel pagina"],
	"faq_spp_quest_1" : ["How do i change my profile picture?", "Hoe verander ik mijn profielfoto?"],
	"faq_spp_quest_2" : ["Basic overview", "Basis overzicht"],

	"faq_hp_ans_1.1" : ["You can navigate through our website using the menu icon in the top left of the screen.", "Je kan navigeren door onze website aan de hand van de menu knop in de linkerbovenhoek."],
	"faq_hp_ans_1.2" : ["A drawer will open, and you'll be able to explore the magnificent world of OverWatch.", "Een menu zal dan openklappen en je kan de prachtige wereld van OverWatch verkennen"],
	"faq_hp_ans_2" : ["In the future the home page might contain cool stuff like graphs that we think you marked as important, statuses of friends you might find interesting, etc.\nThose are just our suggestions, it is up to the company that buys this website to decide what the homepage should do.", "In de toekomst bevat de home pagina misschien coole snufjes zoals grafieken die door jou als belangrijk worden gemarkeerd, statussen van vrienden, enz.\nMaar dat zijn slechts onze suggesties, het is het bedrijf dat deze website koopt dat uiteindelijk beslist wat er mee zal gebeuren."],


	"faq_stp_ans_1" : ["In the first dropdown box you can make a rough selection of the sensors you want to include in your graph.\nThere are three categories: Location, type, and tag. The sensors that have at least one selected location, one selected type and one selected tag will be included in the graph.\n\nThe second dropdown allows you to refine your selection made in the first box. You can view which sensors will be included in the graph and you can deselect them if you don't want them to be in the graph.\n\nThe third dropdown is how you want to view the graph. First you select the start and end date, which will define the length of the graph / the period of time you want to watch.\nThen you'll have to choose how your data will be displayed:\nRaw: The datapoints we kept in our database, the actual data generated by your sensors.\nDays: View the energy consumption per day for the selection of sensors.\nHours, years and months should be analogue to the days.\nEventually you can generate the graph pressing the \"show data\" button.\n\nIn the fourth dropdown you'll be able to view the graphs you generated in that session.\nThey disappear when you refresh the page. But you are able to share those graphs on your wall so you can look back at them later.", "In de eerste dropdown box kan je een ruwe selectie maken van de sensoren waarvan je een grafiek wilth.\nEr zijn 3 Onderdelen: Locatie, type en tag. De sensoren die minstens 1 locatie 1 type en 1 tag hebben die geselecteerd zijn zullen in de grafiek verschijnen. \n\nIn de tweede dropdown box kan je je selectie van de eerste box verfijnen. Je kan kijken welke sensors in de grafiek zullen zitten en je kan ze deselecteren als je niet wilt dat ze in de grafiek zitten.\n\nDe derde dropdown specifieert hoe je de grafiek wilt bekijken: Je selecteert een begin- en einddatum die de lengte van de grafiek definiëren.\nDan moet je kiezen hoe de data zelf wordt opgehaald:\nRuw: De datapunten in onze database, dit is de data van jouw sensors die wij hebben bijgehouden.\nDagen: Bekijk het energieverbruik per dag van de selectie van sensoren.\nUren, jaren, en maanden werken op dezekfde manier als de dagen.\nUiteindelijk kan je de grafiek genereren door op de knop met \"toon data\" te klikken.\n\nIn de vierde dropdown kan je de grafieken bekijken.\nDeze grafieken verdwijnen als je de pagina herlaadt, maar je kan ze op je muur delen zodat je later terug naar de grafiek kan kijken."],
	"faq_stp_ans_2" : ["You can group sensors by selecting the \"aggregate by...\" checkboxes.\nE.g. the aggregate by location checkbox groups all sensors that have the same location.", "Je kan de sensors groeperen door de \"Groepeer per...\" checkboxes aan te zetten.\nBv: De \Groepeer per locatie checkbox groepeert alle sensoren die dezelfde locatie hebben."],

	"faq_sp_ans_1.1" : ["When your page looks something like this:", "Als je pagina er als dit uitziet:"],
	"faq_sp_ans_1.2" : ["chances are you are not using the google chrome browser. You should.", "waarschijnlijk gebruik je niet de Google Chrome browser. Dit doe je best wel."],
	"faq_sp_ans_2" : ["You add a location by pressing one of the \"add...\" buttons in the sensors page.\nYou just fill in the form with your information of the location/sensor.\nPlease note that the number of your location can't contain letters.\nThe description for your location is just for yourself, it's not that significant.\nYou don't have to give tags to your sensors, these are optional.", "Je kan een locatie toevoegen door op de \"sensor/locatie toevoegen\" knop te klikken in de sensors pagina.\nJe vult de formulieren in met jouw informatie van de sensor/locatie.\nHou er rekening mee dat een huisnummer geen letter kan bevatten.\nDe beschrijving bij de locatie is voor jezelf, je kan hier schrijven wat je wilt.\nJe moet geen tags geven aan sensors, deze zijn optioneel."],
	"faq_sp_ans_3.1" : ["You can edit a location/sensor by pressing this button next to the sensor/location you want to edit:", "Je kan een locatie/sensor aanpassen door op dit icoon te klikken (naast de sensor/locatie die je wilt aanpassen):"],
	"faq_sp_ans_3.2" : ["Editing is analogue to creating a new sensor/location. More about ", "Een locatie/sensor aanpassen is analoog aan een nieuwe sensor/locatie aanmaken. Meer over "],
	"faq_sp_ans_4.1" : ["You can delete a location/sensor by pressing this button next to the sensor/location you want to delete:", "Je kan een locatie/sensor verwijderen door op het volgende icoon te klikken (naast de sensor/locatie die je wilt verwijderen.):"],
	"faq_sp_ans_4.2" : ["PLEASE NOTE: all sensors connected to the location will be deleted. If a sensor gets removed, all its data will be gone.", "Hou er rekening mee dat als je een locatie weg doet dan verwijder je ook alle sensors er rond. Als een sensor gedeletet wordt, dan verdwijnt ook de data die de sensor heeft gemaakt."],
	"faq_sp_ans_5" : ["By pressing these arrows you can sort the rows alfabetically/numerical based on the columns:", "Door op het volgende icoon te klikken kan je de rijen van de tabel met sensoren alfabetisch of numerisch rangschikken:"],

	"faq_shp_ans_1" : ["See ", "Bekijk "],
	"faq_shp_ans_2" : ["Making/joining a group", "Groep maken/joinen"],
	"faq_shp_ans_3" : ["Getting new friends", "Vrienden toevoegen"],
	"faq_shp_ans_4" : ["Looking at the wall/profile of groups/friends", "Naar de wall / het profiel van een groep/vriend kijken"],

	"faq_spp_ans_1" : ["How do i change my profile picture?", "Hoe verander ik mijn profielfoto?"],
	"faq_spp_ans_2" : ["Basic overview", "Basis overzicht"],







};
