var html_strings = {
    "electricity": ["Electricity", "Elektriciteit"],
    "water": ["Water", "Water"],
    "gas": ["Gas", "Gas"],
    "temperature": ["Temperature", "Temperatuur"],
    "other": ["Other", "Andere"],
    "homelink": ["Home", "Start"],
    "statisticslink": ["Statistics", "Statistieken"],
    "sensorslink" : ["Sensors", "Sensoren"],
    "sociallink" : ["Social", "Sociaal"],
    "adminlink" : ["Admin", "Beheerder"],
    "reportlink" : ["Report", "Rapport"],
    "datalink" : ["Upload data", "Upload data"],
    "contact": ["Contact ", "Contacteer "],
    "about": ["About ", "Over "],
    "language": ["Language", "Taal"],
    "register": ["Signup", "Registreer"],
    "login": ["Login", "Inloggen"],
    "logout": ["Logout", "Afmelden"],
    "homepage_welcome": ["Welcome to", "Welkom bij"],
    "username": ["Username", "Gebruikersnaam"],
    "firstname": ["Firstname", "Voornaam"],
    "lastname": ["Lastname", "Achternaam"],
    "password": ["Password", "Paswoord"],
    "privacy": ["Privacy & Terms", "Privacy & Condities"], 
    "required_field": ["This field is required", "Dit veld is verplicht"],
    "login_error": ["Wrong username or password!", "Foute gebruikersnaam of paswoord!"],
    "back": ["Back", "Terug"],
    "invalid_email": ["Please input a valid email address", "Gelieve een geldig emailadres in te geven"], 
    "invalid_password": ["Password must contain at least 8 characters", "Paswoord moet minstens 8 tekens bevatten"],
    "signup_error": ["Email already exists.\nPlease login with your account.", "Emailadres bestaat al.\nGelieve in te loggen op dit account."],
    "description": ["Description", "Beschrijving"],
    "country": ["Country", "Land"],
    "city": ["City", "Stad"],
    "postalcode": ["ZIP / Postal Code", "Postcode"],
    "street": ["Street", "Straat"],
    "number": ["Number", "Huisnummer"],
    "unit_price": ["Usage cost (per unit)", "Verbruikskost (per eenheid)"],
    "edit_location": ["Edit location", "Locatie bewerken"],
    "add_location": ["Add location", "Locatie toevoegen"],
    "del_location": ["Delete location", "Locatie verwijderen"],
    "edit_sensor": ["Edit sensor", "Sensor bewerken"],
    "del_sensor": ["Delete sensor", "Sensor verwijderen"],
    "add_sensor": ["Add sensor", "Sensor toevoegen"],
    "save_changes": ["Save", "Opslaan"],
    "name": ["Name", "Naam"],
    "pick_loc": ["Choose your location", "Kies uw locatie"],
    "pick_type": ["Choose your type", "Kies uw type"],
    "locations": ["Locations", "Locaties"],
    "location": ["Location", "Locatie"],
    "mark_unimportant": ["Mark as unimportant", "Markeren als onbelangrijk"],
    "mark_important": ["Mark as important", "Markeren als belangrijk"],
    "confirm_title": ["Confirmation", "Bevestiging"],
    "confirm_text": ["This item will be removed permanently from your interface. Together with all its refered objects!!\nAre you sure you want to continue?", 
                     "Dit item zal voorgoed verwijderd worden uit uw interface. Samen met alle gerefereerde objecten!!\nBent u zeker dat u wilt doorgaan?"],
    "continue": ["Continue", "Doorgaan"],
    "cancel": ["Cancel", "Annuleren"],
    "share" : ["Share", "Deel"],
    "aggregate_loc" : ["Aggregate by location", "Groepeer per locatie"],
    "aggregate_type" : ["Aggregate by type", "Groepeer per type"],
    "aggregate_tag" : ["Aggregate by tag", "Groepeer per tag"],
    "aggregate_eur_per_unit" : ["Aggregate by Euro per Unit", "Groepeer per euro per unit"],
    "aggregate_user" : ["Aggregate by user", "Groepeer per user"],
    "open" : ["Open", "Openen"],
    "close" : ["Close", "Sluiten"],
    "delete_comment" : ["Delete comment", "Comment verwijderen"],
    "show_comments" : ["Show comments", "Comments tonen"],
    "hide_comments" : ["Hide comments", "Comments verbergen"],
    "comment_status" : ["Comment on this status...", "Comment op deze status..."],
    "find_friends" : ["Find friends", "Vrienden zoeken"],
    "create_group" : ["Create group", "Groep maken"],
    "join_group" : ["Join group", "Lid worden van een groep"],
    "group_name" : ["Group name", "Groepsnaam"],
    "group_public" : ["Public group", "Publieke groep"],
    "group_secret" : ["Secret group", "Geheime groep"],
    "create" : ["Create", "Aanmaken"],
    "my_profile" : ["My Profile", "Mijn Profiel"],
    "my_friends" : ["My Friends", "Mijn Vrienden"],
    "no_location_title" : ["No Locations Available", "Geen Locaties Beschikbaar"],
    "no_location_text" : ["It is not allowed to add sensors when you have not added any locations yet.\nPlease add a location first.",
                          "Het is niet toegestaan om sensors toe te voegen wanneer u nog geen locaties heeft toegevoegd.\nGelieve eerst een locatie aan te maken."],
    "ok" : ["Okay", "OK"],
    "add_friend" : ["Add friend", "Vriend toevoegen"],
    "box1_title" : ["Select sensors by locations, types or tags", "Selecteer sensors op basis van locaties, types or tags"],
    "box1_title_admin" : ["Select sensors by users", "Selecteer sensors op basis van users"],
    "box2_title" : ["Refine your selection by selecting sensors individually", "Verfijn uw zoekopdracht door sensors individueel te selecteren"],
    "box3_title" : ["Choose the timespan", "Kies de tijdspanne"],
    "box4_title" : ["Resulting graphs", "Resulterende grafieken"],
    "show_data" : ["Show data", "Toon data"],
    "merge_checkbox" : ["Merge if possible", "Samenvoegen indien mogelijk"],
    "show_data_from" : ["Show data from ", "Toon data van "],
    "amount" : ["number", "aantal"],
    "amount_help" : ["Amount of days/months/years you want to look back in time", "Aantal dagen/maanden/jaren terug, waarvan u de data wilt bekijken"],
    "start_date" : ["Start date", "Start datum"],
    "end_date" : ["End date", "Eind datum"],
    "pick_time_unit" : ["Pick a time unit", "Kies een tijdseenheid"],
    "raw" : ["Raw", "Ruw"],
    "hours" : ["Hours", "Uren"],
    "days" : ["Days", "Dagen"],
    "months" : ["Months", "Maanden"],
    "years" : ["Years", "Jaren"],
    "upload_file" : ["Upload a data file", "Laad een data file in"],
    "share_title" : ["Share the graph", "Deel de grafiek"],
    "share_text" : ["You can choose to post this graph on your own wall, visible to all of your friends, or in a group, visible to all the group members.",
                    "Je kan kiezen om deze grafiek op je prikbord te plaatsen, zichtbaar voor al je vrienden, of in een groep, zichtbaar voor alle leden."],
    "share_with" : ["Share with ", "Deel met "],
    "wall" : ["Wall", "Prikbord"],
    "pick_share" : ["choose a method", "kies een methode"],
    "data_title" : ["Upload data", "Upload data"],
    "data_text" : ["Generate a new data file through our elecsim script and upload this file with the following button.",
                   "Genereer een nieuwe data file met ons elecsim script en upload deze file met onderstaande knop."],
    "send" : ["Send", "Versturen"],
    "send_error" : ["Something went wrong while uploading your file, please try again", "Er ging iets mis bij het sturen van uw file, probeer aub opnieuw"],
    "down_config" : ["Download configuration file", "Download configuratie file"],
    "users" : ["Users", "Gebruikers"],
    "delete_friend" : ["Delete friend", "Vriend verwijderen"],
    "until" : ["until", "tot"],
    "input_status" : ["How are you feeling today?", "Wat ben je aan het doen?"],
    "post" : ["Post", "Plaats"],
    "delete_status" : ["Delete status", "Status verwijderen"],
    "group" : ["Group", "Groep"],
    "pick_group" : ["Pick group", "Kies een groep"],
    "input_status_group": ["What do you want to share with the group?", "Wat ben je aan het doen?"],
    "post_group": ["Post in group", "Gooi het in de groep"],
    "own_status" : ["Own status", "Eigen status"],
    "friend_status" : ["Status from ", "Status van "],
    "posted_on" : ["Posted on: ", "Geplaatst op: "],
    "no_tag" : ["No tags", "Geen tags"],
    "welcome_group" : ["Welcome in group: ", "Welkom in de groep: "],
    "members" : ["Members: ", "Leden: "],
    "leave_group" : ["Leave group", "Groep verlaten"],
    "report_title" : ["Title (click and type to make a title)", "Titel (klik en typ om een titel te maken)"],
    "report_comment" : ["comment (click and type to make a comment)", "comment (klik en typ om een comment te maken)"],
    "report_final_comment" : ["comment (click and type to make a final comment)", "comment (klik en typ om een finale comment te maken)"],
    "graph" : ["Graph", "Grafiek"];
};
