var html_strings = {
    "electricity_type": ["Electricity", "Elektriciteit"],
    "water_type": ["Water", "Water"],
    "gas_type": ["Gas", "Gas"],
    "temperature_type": ["Temperature", "Temperatuur"],
    "other_type": ["Other", "Andere"],
    "homelink": ["Home", "Start"],
    "statisticslink": ["Statistics", "Statistieken"],
    "sensorslink": ["Sensors", "Sensoren"],
    "sociallink": ["Social", "Sociaal"],
    "contact": ["Contact ", "Contacteer "],
    "about": ["About ", "Over "],
    "language": ["Language", "Taal"],
    "register": ["Signup", "Registreer"],
    "login": ["Login", "Inloggen"],
    "logout": ["Logout", "Afmelden"],
    "homepage_welcome": ["Welcome to", "Welkom bij"],
    "username": ["Username", "Gebruikersnaam"],
    "firstname": ["Firstname", "Voornaam"],
    "lastname": ["Lastname", "Achternaam"],
    "password": ["Password", "Paswoord"],
    "privacy": ["Privacy & Terms", "Privacy & Condities"], 
    "required_field": ["This field is required", "Dit veld is verplicht"],
    "login_error": ["Wrong username or password!", "Foute gebruikersnaam of paswoord!"],
    "back": ["Back", "Terug"],
    "invalid_email": ["Please input a valid email address", "Gelieve een geldig emailadres in te geven"], 
    "invalid_password": ["Password must contain at least 8 characters", "Paswoord moet minstens 8 tekens bevatten"],
    "signup_error": ["Email already exists.\nPlease login with your account.", "Emailadres bestaat al.\nGelieve in te loggen op dit account."],
    "description": ["Description", "Beschrijving"],
    "country": ["Country", "Land"],
    "city": ["City", "Stad"],
    "postalcode": ["ZIP / Postal Code", "Postcode"],
    "street": ["Street", "Straat"],
    "number": ["Number", "Huisnummer"],
    "elec_price": ["Cost Per Electricity Unit", "Kost per elektriciteitseenheid"],
    "unit price": ["Usage cost (per unit)", "Verbruikskost (per eenheid⁾"],
    "edit_location": ["Edit location", "Locatie bewerken"],
    "add_location": ["Add location", "Locatie toevoegen"],
    "del_location": ["Delete location", "Locatie verwijderen"],
    "edit_sensor": ["Edit sensor", "Sensor bewerken"],
    "del_sensor": ["Delete sensor", "Sensor verwijderen"],
    "add_sensor": ["Add sensor", "Sensor toevoegen"],
    "save_changes": ["Save", "Opslaan"],
    "name": ["Name", "Naam"],
    "pick_loc": ["Choose your location", "Kies uw locatie"],
    "pick_type": ["Choose your type", "Kies uw type"],
    "locations": ["Locations", "Locaties"],
    "location": ["Location", "Locatie"],
    "mark_unimportant": ["Mark as unimportant", "Markeren als onbelangrijk"],
    "mark_important": ["Mark as important", "Markeren als belangrijk"],
    "confirm_title": ["Confirmation", "Bevestiging"],
    "confirm_text": ["This item will be removed permanently from your interface.\nAre you sure you want to continue?", 
    "Dit item zal voorgoed verwijderd worden uit uw interface.\nBent u zeker dat u wilt doorgaan?"],
    "continue": ["Continue", "Doorgaan"],
    "cancel": ["Cancel", "Annuleren"],
    "share" : ["Share", "Deel"],
    "aggregate_loc" : ["Aggregate by location", "Groepeer per locatie"],
    "aggregate_type" : ["Aggregate by type", "Groepeer per type"],
    "aggregate_sensor" : ["Aggregate by sensor", "Groepeer per sensor"],
    "open" : ["Open", "Openen"],
    "close" : ["Close", "Sluiten"],
    "delete_comment" : ["Delete comment", "Comment verwijderen"],
    "show_comments" : ["Show comments", "Comments tonen"],
    "comment_status" : ["Comment on this status...", "Comment op deze status..."],
    "find_friends" : ["Find friends", "Vrienden zoeken"],
    "create_group" : ["Create group", "Groep maken"],
    "group_name" : ["Group name", "Groepsnaam"],
    "group_public" : ["Public group", "Publieke groep"],
    "group_secret" : ["Secret group", "Geheime groep"],
    "create" : ["Create", "Aanmaken"],s
};
